In [1]:
import torch 
import numpy as np

In [2]:
# Input(temp,rainnfall,humidity)
inputs= np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]],dtype='float32')

In [3]:
#Targest(apples, oranges)
targets=np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]],dtype='float32')

In [4]:
# Numpy array to tensors
targets=torch.from_numpy(targets)
inputs=torch.from_numpy(inputs)
print(targets)
print(inputs)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [5]:
#Creating random Weights and Biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(b)
print(w)

tensor([-0.8734,  0.9244], requires_grad=True)
tensor([[-0.8011, -0.4610, -0.1354],
        [-1.1801, -0.1219, -1.7094]], requires_grad=True)


In [6]:
#Define the Model
def model(x):
    return x@w.t()+b

In [7]:
#Generate predictions
pre=model(inputs)
print(pre)

tensor([[ -96.0614, -166.8889],
        [-123.0051, -226.5865],
        [-140.1948, -217.2155],
        [-107.4161, -187.9297],
        [-109.8818, -211.8563]], grad_fn=<AddBackward0>)


In [8]:
#Create Loss function (MSE loss)
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [9]:
#Train the model with epochs
for i in range(750):
    pre=model(inputs)
    loss=mse(pre,targets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*1e-5
        b-=b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()

In [10]:
pre=model(inputs)
loss=mse(pre,targets)
print(loss)

tensor(40.5915, grad_fn=<DivBackward0>)


In [11]:
#Predictions
pre

tensor([[ 57.1400,  71.2257],
        [ 81.6683,  94.2908],
        [119.9557, 145.9965],
        [ 21.7248,  40.7204],
        [100.4372, 106.0638]], grad_fn=<AddBackward0>)

In [12]:
#Actual Value
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])